name: Remove old artifacts

on:
  schedule:
    - cron: '0 1 * * *' # once a day
  workflow_dispatch: { }

jobs:
  remove-old-artifacts:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Remove old artifacts
        uses: c-hive/gha-remove-artifacts@v1
        with:
          age: '0 seconds'
          skip-tags: true
          skip-recent: 5